# Generated by Django 3.0.7 on 2021-08-24 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil_nome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('sobrenome', models.CharField(max_length=50)),
                ('data_nascimento', models.DateTimeField()),
                ('endereco', models.CharField(max_length=50)),
                ('cartão', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='cartão',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='data_nascimento',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='sobrenome',
        ),
    ]
