# Generated by Django 3.0.7 on 2021-08-26 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_perfil_nome_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacao',
            name='modo',
            field=models.IntegerField(choices=[(0, 'Presencial'), (1, 'Naopresencial')], default=1),
            preserve_default=False,
        ),
    ]
