# Generated by Django 3.0.7 on 2021-08-26 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_publicacao_modo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=1000)),
                ('publicacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Publicacao')),
            ],
        ),
    ]
